<?php

/*
|--------------------------------------------------------------------------
| Calendar Language Lines / RO
|--------------------------------------------------------------------------
|         _________  _______          _       ____  _____  ________
|        |  _   _  ||_   __ \        / \     |_   \|_   _||_   __  |
|        |_/ | | \_|  | |__) |      / _ \      |   \ | |    | |_ \_|
|            | |      |  __ /      / ___ \     | |\ \| |    |  _| _
|           _| |_    _| |  \ \_  _/ /   \ \_  _| |_\   |_  _| |__/ |
|          |_____|  |____| |___||____| |____||_____|\____||________|
|                                                      by custura.de
*/

return [
    'approved_at' => 'Aprobat la',
    'approved_by' => 'Aprobat de',
    'are_you_sure_update?' => 'Sunteți sigur că doriți să actualizați această întâlnire?',
    'blue' => 'Albastru',
    'cancel' => 'Anuleaza',
    'clients' => 'Clienti',
    'color' => 'Culoare',
    'colors' => 'Culori',
    'confirm' => 'Confirma',
    'create' => 'Creaza',
    'created_at' => 'Creat la',
    'created_by' => 'Creat de',
    'created_successfully' => 'Creat cu succes',
    'date_is_in_future' => 'Data este în viitor.',
    'date_range_is_locked' => 'Data este blocată.',
    'day_total' => 'Total pe zi',
    'delete' => 'Sterge',
    'details' => 'Detalii',
    'details_regrading_the_appointment' => 'Detalii despre programare.',
    'disapproved_at' => 'Dezaprobat la',
    'disapproved_by' => 'Dezaprobat de',
    'duration' => 'Durata',
    'duration_important' => 'Important: Data folositi campul "Durata" trebuie folosit de la inceputul schimbului pana la final incusiv pauza.',
    'edit' => 'Modifica',
    'end_at' => 'Sfârșește la',
    'friday' => 'Vineri',
    'holiday' => 'Sarbatoare',
    'medical' => 'Medical',
    'monday' => 'Luni',
    'month' => 'Lună',
    'month_total' => 'Total lunar',
    'monthly_quotas' => 'Cote Lunare',
    'no_notes' => 'Nu sunt notiţe.',
    'no_permission' => 'Nu ai permisiunea necesara.',
    'no_title' => 'Nu există titlu.',
    'not_approved' => 'Neaprobat',
    'not_provided' => 'Nesetat',
    'notes' => 'Notiţe',
    'orange' => 'Portocaliu',
    'over_balance' => 'Peste balanţă',
    'over_quota' => 'Peste cotă',
    'overlapping_records_are_not_allowed' => 'Înregistrările suprapuse nu sunt permise.',
    'pause' => 'Pauza',
    'projects' => 'Poriecte',
    'quota' => 'Cotă',
    'red' => 'Rosu',
    'remaining_balance' => 'Balanţă ramasă',
    'remaining_quota' => 'Cotă ramasă',
    'saturday' => 'Sambata',
    'save' => 'Salveaza',
    'scheduled_at' => 'Programat la',
    'select_client' => 'Selecteaza Client',
    'select_color' => 'Selecteaza Culoare',
    'select_project' => 'Selecteaza Proiect',
    'select_task' => 'Selecteaza Atribuţie',
    'select_template' => 'Selecteaza Șablon',
    'set_to_day' => 'Setați-l la ziua selectată',
    'show_more' => 'Arata mai mult',
    'start_at' => 'Incepe la',
    'sunday' => 'Duminica',
    'tasks' => 'Atribuţii',
    'templates' => 'Șabloane',
    'this_action_is_unauthorized_on' => 'Această acțiune este neautorizată pe ',
    'this_action_is_unauthorized_on_approved_appointment' => 'Această acțiune este neautorizată pe o programare aprobată.',
    'thursday' => 'Joi',
    'today' => 'Azi',
    'tuesday' => 'Marti',
    'uncompleted' => 'NECOMPLATĂ',
    'unschedule' => 'Anulați programarea',
    'unscheduled_events' => 'Evenimente neprogramate',
    'update' => 'Actualizeaza',
    'update_appointment' => 'Actualizați Programarea',
    'updated_at' => 'Modificat la',
    'updated_successfully' => 'Modificat cu succes',
    'vacation' => 'Concediu',
    'wednesday' => 'Miercuri',
    'week_total' => 'Total saptamanal',
    'work' => 'Muncă',
    'worked_time' => 'Timp de lucru',
    'year' => 'An',
    'yellow' => 'Galben',
];
